jobs:
  - name: mirror-ghostunnel
    plan:
      - get: aws-management-infrastructure
      - get: ghostunnel-release
        trigger: true
        params:
          globs:
            - "ghostunnel-v*-linux-amd64-with-pkcs11"
      - .: (( inject meta.plan.terraform-output-management ))
      - .: (( inject meta.plan.mirror-artefact ))
        input_mapping:
          artefact-release: ghostunnel-release
        config:
          params:
            ARTEFACT_DIR: "ghostunnel"
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
