jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-aws-bgdc-interface
        trigger: true
        passed:
          - qa
      - get: al2-emr-ami
        trigger: true
        passed:
          - qa
      - get: emr-launcher-release
        trigger: true
        passed:
          - qa
      - get: bgdc-base-ami
        trigger: false
        passed:
          - qa
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'preprod'
