jobs:
  - name: start-cluster-development
    plan:
      - in_parallel:
        - .: (( inject meta.plan.start-cluster ))
          config:
            params:
              AWS_ACC: ((aws_account.development))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
              CLUSTER_NAME: bgdc-interface
        - .: (( inject meta.plan.start-cluster ))
          config:
            params:
              AWS_ACC: ((aws_account.development))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
              CLUSTER_NAME: bgdc-interface-metadata

  - name: start-cluster-qa
    plan:
      - in_parallel:
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
                CLUSTER_NAME: bgdc-interface
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
                CLUSTER_NAME: bgdc-interface-metadata

  - name: start-cluster-integration
    plan:
      - in_parallel:
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
                CLUSTER_NAME: bgdc-interface
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
                CLUSTER_NAME: bgdc-interface-metadata

  - name: start-cluster-preprod
    plan:
      - in_parallel:
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
                CLUSTER_NAME: bgdc-interface
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
                CLUSTER_NAME: bgdc-interface-metadata

  - name: start-cluster-production
    plan:
      - in_parallel:
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
                CLUSTER_NAME: bgdc-interface
          - .: (( inject meta.plan.start-cluster ))
            config:
              params:
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
                CLUSTER_NAME: bgdc-interface-metadata
